name: Deploy API ParóquiaON to Vercel

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/api-paroquiaon/**'
      - 'backend/gateway/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/api-paroquiaon/**'
      - 'backend/gateway/**'

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'backend/api-paroquiaon/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd backend/api-paroquiaon
        npm install
        
    - name: Build project
      run: |
        cd backend/api-paroquiaon
        npm run build || echo "No build script found, continuing..."
        
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        working-directory: backend/api-paroquiaon
        vercel-args: '--prod'

  deploy-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd frontend
        npm install
        
    - name: Build frontend
      run: |
        cd frontend
        npm run build
        
    - name: Deploy Frontend to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID_FRONTEND }}
        working-directory: frontend
        vercel-args: '--prod'